### PR TITLE
Fix for Issue #03

### PR DESCRIPTION
**Pull request by tbogdala**
This patch calls glewInit() to initialize GL and also supplies a build file for mingw64 on Windows. 

Note the build file still doesn't build ytrace because of pthread issues when not using MSVC.

### CODE REVIEW

**Comment by xelatihy** [comment]
Do you know if there is a problem in ytrace too, or just yshade?
I'd like to fix both for your case in case the problem is for each.

**Comment by xelatihy** [comment]
I would rather know where this comes from since the code should work (and on does on my machine) before accepting a fix.

**Comment by tbogdala** [comment]
glewInit() was needed for sure in yshade.

For the ytrace issue, the last I tracked it to roughly apps/ytrace.c:43

```
#ifndef _MSC_VER
#include "ext/thpool.c"
#include "ext/thpool.h"
#else
typedef int threadpool;
static inline threadpool
thpool_init(int n) {
    return 0;
}
static inline void
thpool_destroy(threadpool pool) {}
static inline void
thpool_wait(threadpool pool) {}
static inline void
thpool_add_work(threadpool pool, void* (*fn)(void*), void* ctx) {
    fn(ctx);
}

#endif
```

If it's not MSVC, then it tries to use the headers, and then it cant find the definition for SIGUSR1. That's the last I looked into it. I believe I seen some google searches that indicated it might be a portability issue.

**Comment by xelatihy** [comment]
I'll look into this soon. I am chainging the internals of yocto right now, so I will be looking at this once the new internals are good.

**Pull request closed without merging**
