### PR TITLE
Yshader fix for lights

### PR DESCRIPTION
**Pull request by tbogdala**
This simply bypasses the rendering of point shapes.

### CODE REVIEW

**Comment by xelatihy** [comment]
Can you mention why the rendering of points is an issue?
In general, in Physically-Based Rendering, lights are always visible.

**Comment by tbogdala** [comment]
Sure. This is related to issue #5 and I have more details there.

https://github.com/xelatihy/yocto-gl/issues/5

Basically, the draw call was segfaulting on my machine. The patch I have disables drawing of point shapes, but as I indicated, I was worried this wasn't the right solution. I ran out of time to play around with this yesterday and I would have had to dig into it quite a bit further to try and find a better solution.

**Comment by xelatihy** [comment]
In am accepting the changes on glew, exept I will merge them in a different commit (to make it compile on OSX too). For the mingw64 it seems there are still concerns about building ytrace, which is the main app. So I better not merge that just yet.

**Comment by tbogdala** [comment]
That's true. I didn't get ytrace working yet with mingw, but didn't investigate either.

**Pull request closed without merging**
